### ISSUE TITLE
Show Top 20 Projects on the Home View

### ISSUE THREAD

**Issue by camelspeed** [Project-Heimdall/home#14]
We want to show the Top 20 so users can see what is popular and active in the firm.  We are also aiming to provide some incentive to folks to work hard and create meaningful and useful projects so that they become popular and show up on the front view.  This is the first foray into incentives to help drive correct usage and competition.

**Ranking Algorithm**
`rank = num(stars) + num(contributors) + num(watchers) + num(commits) + num(releases)`

**Acceptance Criteria**
- [ ] Top 20 shown by ranking algorithm from highest rank to lowest.  his is the default and only sort order for now.
- [ ] No pagination.  All data is present at once
- [ ] Data is shown as cards with cards showing
 * stars, contributors, watchers, commits, releases
 * org name, project name, project desc, code language
 * link to view readme
- [ ] Display 2 cards per row per the approved card design and layout.

**Comment by herrjosua** [comment]
Adding approved design.

![popular screen 1](https://cloud.githubusercontent.com/assets/1341786/16842823/d4bc6878-49ac-11e6-8de4-44142167cefb.png)
