### ISSUE TITLE
Usability MVP Criteria

### ISSUE THREAD

**Issue by camelspeed** [Project-Heimdall/home#197]
- [x] #205 Updated the placeholder text in the main search to something along the lines of `Search for projects, and languages...` Also applies the mini search bar within the Navbar.
- [ ] #176 Add tooltip's to the user nav icons (@rebecca-allegar Is this the same issue?)
    - [x] Search
    - [x] Feedback
- [x] #206 Change the Feedback modal's title to something along the lines of `Get involved with Stage`
- [x] #210 Change the `Give Feedback` menu item
- [x] #204 Fix the scrollbar issue with the middle button.
- [x] #204 Remove Survey link (Might resolve previous issue with Scroll bar)
- [x] #207 On the `Project Details` view add a title to the Github section like on the cards on the home page
- [x] #208 Change the Build section in `Health Statistics` to a get involve with Stage` link or remove
- [x] #191 Remove the Fortify link and Fortify coming soon icon
- [x] #208 Restored the divider line between Quality and Security Sections. Possibly combine them into a single section called `SonarQube`?
    - [x] If we are combing into a single section called `SonarQube` the link should be moved to the right similar to how to `Github` links is done on the home page. 
- [x] #213 Remove `log off` menu item from the user drop-down menu

**Comment by herrjosua** [comment]
Waiting for approval on the changes to the `Project Details` view, and the Avatar change.

**Comment by herrjosua** [comment]
Merged changes for #186. Once the PR has been merged these issues can be closed.

**Comment by herrjosua** [comment]
Verified issue has been resolved on `PROD`. Closing this issue.
