### ISSUE TITLE
Story and Task Breakdown Epic #5 (Explore Projects)

### ISSUE THREAD

**Issue by camelspeed** [Project-Heimdall/home#42]
- [ ] Pull **all** data and order by Org Name then Project Name (Default)
- [ ] Be able to Filter results on the UI by Organization or Language or Both
- [ ] Be able to Sort results by the Default, Stars, Watchers, Commits, Contributors, and Releases
- [ ] Go to Project Details.
