### ISSUE TITLE
Story and Task Breakdown Epic #3 (Search)

### ISSUE THREAD

**Issue by camelspeed** [Project-Heimdall/home#43]
- [ ] Define which capabilities of Search will be used
 - [ ] autocorrect
 - [ ] autocomplete
 - [ ] what else (synonyms, partial matching..)?
 - [ ] how will they be ranked for ordering upon retrieval (Default Sort Order)
- [ ] Searching with no criteria will behave identically to Explore
- [ ] All data comes to the UI
- [ ] Filter by Organization or Code Language or Both
- [ ] Sort by Watchers, Commits, Contributors, Releases, Stars, Default
