### ISSUE TITLE
Story and Task Breakdown Epic #7 (Project Header Details)

### ISSUE THREAD

**Issue by camelspeed** [Project-Heimdall/home#44]
- [ ] From Popular View, Explore View, and Search Results View be able to view the project's header details.
- [ ] Update projects index to include contributors, owners, and forks.
- [ ] Update API to return project info by ID
