### ISSUE TITLE
User would like to explore all projects by browsing them.

### ISSUE THREAD

**Issue by camelspeed** [Project-Heimdall/home#5]
Identical to the Popular view except the data pulled is the entire dataset we currently have and not the 
**Top 20**.

**Acceptance Criteria**
- [ ] Default order is by Org Name then Project Name
- [ ] No pagination.  All data is present at once
- [ ] Data is shown as cards with cards showing
 * stars, contributors, watchers, commits, releases
 * org name, project name, project desc, code language
 * link to view readme
- [ ] Display 2 cards per row per the approved card design and layout.
