### ISSUE TITLE
User would like autocomplete and autocorrect assistance when searching

### ISSUE THREAD

**Issue by camelspeed** [Project-Heimdall/home#50]
- [ ] Assist the user by providing autocomplete and autocorrect suggestions as they are entering search terms.
- [ ] If a user enters incorrect spelled search terms and submits the system will run 2 searches:
 - [ ] One with correct spellings (suggested as an alternative)
 - [ ] One with the spellings as-is (returned first)
