### ISSUE TITLE
User would like to explore Popular Projects

### ISSUE THREAD

**Issue by camelspeed** [Project-Heimdall/home#6]
Popular projects will be determined by some algorithm but they are the projects that are typically most active with the most contributors, stars, and references.

We are using package time configuration because these settings will not be changing often.  If there is a more dynamic need then it will be come runtime configurable but for now package time is fine. Do not hard code the values in the view or in an obscure place.

**Acceptance Criteria**
- [ ] Top X projects are displayed and listed by their ranking from highest to lowest.
- [ ] The number of projects X is 20 and should be a package time configuration
- [ ] Search is available
- [ ] Filters (tbd) and result statistics are available.
- [ ] User should be able to come to the Popular page from any view.
- [ ] Projects are pulled from the Booz Allen, Booz-Allen-Hamilton, Netflix Repositories.  The orgs for consideration should be a package time configuration.
