### ISSUE TITLE
Integration With Other Repos

### ISSUE THREAD

**Issue by camelspeed** [Project-Heimdall/home#66]
- [ ] Integrate with DockerHub
 - [ ] Netflix https://hub.docker.com/u/netflixoss/
 - [ ] boozallen
 - [ ] booz-allen-hamilton
 - [ ] 18F
 - [ ] Spring Projects
 - [ ] Durandal Project
 - [ ] Elastic https://hub.docker.com/_/elasticsearch/ https://hub.docker.com/_/logstash/
 - [ ] NodeJS https://hub.docker.com/_/node/
 - [ ] JQuery
- [ ] Integrate with SonarQube
- [ ] Integrate with TravisCI
