### ISSUE TITLE
User views the Project Header Details

### ISSUE THREAD

**Issue by camelspeed** [Project-Heimdall/home#7]
A software project is comprised of many components and artifacts. The details view allows a user to take a deeper dive into the anatomy and composition of a project, the project's intent and purpose, and it's relationship to other projects.  This story is concerned with the core Header Details of the project.

**Acceptance Criteria**
- [ ] Display Org Name, Project Name, Project Description, Project Language
- [ ] GitHub Stats: # commits, # releases, #contributors
- [ ] View Readme link
