### ISSUE TITLE
Research approach to proper Project Dependencies Architecture

### ISSUE THREAD

**Issue by camelspeed** [Project-Heimdall/home#73]
Currently the solution goes directly to GitHub and processes the dependencies for a Java POM project but it is not flexible or scalable because it expects only 1 POM at the root and can only handle Java POM projects, which it does blindly.

Our solution for this iteration has to handle:
- [ ] offline processing of data.  Processing can be manual (human runs script against known sources) and once we prove end to end we start considering other avenues (e.g. Logstash plugins)
- [ ] API server will provide data to clients.  Clients do not directly go to the source.  We will need to consider a graph database (e.g. Neo4J)
- [ ] Dependency data needs to be searchable (i.e. Data stored in ES)
- [ ] For now we need to research enough to support Java Maven and Gradle projects at 1 level deep (all dependency artifacts in the project need to be discovered).
