### ISSUE TITLE
User can explore direct project dependencies for Java Maven projects from the Project Details View

### ISSUE THREAD

**Issue by camelspeed** [Project-Heimdall/home#9]
Each project has relationships to other projects and these are usually define in 1 or more Java Maven build files called Project Object Model (POM) file.  Depending on the hierarchy of the project there can be several POM files, each of which describes their dependencies.

The goal of this feature is to inspect all first level (aka direct) dependencies with version numbers and allow the user to see this data from the Project Details view.

**Acceptance Criteria**
- [ ] View shows the info on demand (eg modal view) and not part of the Project Details view
- [ ] Number of project dependencies is shown as part of Project Details view
- [ ] Only direct dependencies with version numbers are shown
